DROP TABLE comm_products CASCADE CONSTRAINTS;;
DROP TABLE comm_products_stock CASCADE CONSTRAINTS;;
DROP TABLE comm_customers CASCADE CONSTRAINTS;;
DROP TABLE comm_order CASCADE CONSTRAINTS;;
DROP TABLE comm_order_items CASCADE CONSTRAINTS;;
DROP TABLE comm_shoppingCart CASCADE CONSTRAINTS;;
DROP TABLE comm_cart_items CASCADE CONSTRAINTS;;